import { Router } from "express";
import service from "../../services/commissionService.js";
import notificationService from "../../services/commissionNotificationService.js";
const router=Router();
const enviar=async(res,fn,status=200)=>{try{res.status(status).json(await fn());}catch(e){console.error(e);res.status(400).json({error:e.message});}};
router.get("/dashboard",(q,s)=>enviar(s,()=>service.dashboard()));
router.get("/technicians",(q,s)=>enviar(s,()=>service.listarTecnicos()));
router.post("/technicians",(q,s)=>enviar(s,()=>service.salvarTecnico(q.body),201));
router.put("/technicians/:id",(q,s)=>enviar(s,()=>service.salvarTecnico(q.body,q.params.id)));
router.get("/entries",(q,s)=>enviar(s,()=>service.listarComissoes()));
router.get("/imports",(q,s)=>enviar(s,()=>service.listarImportacoes()));
router.get("/imports/:id/delete-preview",(q,s)=>enviar(s,()=>service.impactoExclusaoImportacao(Number(q.params.id))));
router.delete("/imports/:id",(q,s)=>enviar(s,()=>service.excluirImportacao(Number(q.params.id),q.body.mode)));
router.post("/imports",(q,s)=>enviar(s,()=>service.importar(q.body),201));
router.post("/imports/preview",(q,s)=>enviar(s,()=>service.preverImportacao(q.body)));
router.post("/imports/:id/notify",(q,s)=>enviar(s,()=>notificationService.createImportJob(Number(q.params.id),"Administrador local",false),202));
router.post("/imports/:id/retry-notifications",(q,s)=>enviar(s,()=>notificationService.createImportJob(Number(q.params.id),"Administrador local",true),202));
router.get("/notifications/history",(q,s)=>enviar(s,()=>notificationService.history()));
router.get("/notifications/jobs/:id",(q,s)=>enviar(s,()=>notificationService.getJob(Number(q.params.id))));
router.post("/notifications/jobs/:id/cancel",(q,s)=>enviar(s,()=>notificationService.cancel(Number(q.params.id))));
router.get("/technicians/:id/balance-preview",(q,s)=>enviar(s,()=>notificationService.previewBalance(Number(q.params.id))));
router.post("/technicians/balance-preview",(q,s)=>enviar(s,()=>notificationService.previewBulk(q.body.technicianIds)));
router.post("/technicians/send-balance",(q,s)=>enviar(s,()=>notificationService.createBalanceJob(q.body.technicianIds,"Administrador local"),202));
router.get("/credits/:technicianId",(q,s)=>enviar(s,()=>service.creditosDisponiveis(q.params.technicianId)));
router.get("/requests",(q,s)=>enviar(s,()=>service.listarSolicitacoes()));
router.post("/requests",(q,s)=>enviar(s,()=>service.criarSolicitacao(q.body),201));
export default router;
