import { Router } from "express";
import service from "../../services/commissionService.js";
const router=Router();
const enviar=async(res,fn,status=200)=>{try{res.status(status).json(await fn());}catch(e){console.error(e);res.status(400).json({error:e.message});}};
router.get("/dashboard",(q,s)=>enviar(s,()=>service.dashboard()));
router.get("/technicians",(q,s)=>enviar(s,()=>service.listarTecnicos()));
router.post("/technicians",(q,s)=>enviar(s,()=>service.salvarTecnico(q.body),201));
router.put("/technicians/:id",(q,s)=>enviar(s,()=>service.salvarTecnico(q.body,q.params.id)));
router.get("/entries",(q,s)=>enviar(s,()=>service.listarComissoes()));
router.get("/imports",(q,s)=>enviar(s,()=>service.listarImportacoes()));
router.post("/imports",(q,s)=>enviar(s,()=>service.importar(q.body),201));
router.get("/credits/:technicianId",(q,s)=>enviar(s,()=>service.creditosDisponiveis(q.params.technicianId)));
router.get("/requests",(q,s)=>enviar(s,()=>service.listarSolicitacoes()));
router.post("/requests",(q,s)=>enviar(s,()=>service.criarSolicitacao(q.body),201));
export default router;
